function [] = main()

disp('loading paths')
addpath(genpath('/N/u/hayashis/BigRed2/git/vistasoft'))
addpath(genpath('/N/u/hayashis/BigRed2/git/jsonlab'))

% load my own config.json
config = loadjson('config.json');

% run dtiInit
dwParams = dtiInitParams(...
    'clobber',1, ...
    'phaseEncodeDir',2, ...
    'bvecsFile',config.bvecs, ...
    'bvalsFile',config.bvals, ...
    'dt6BaseName','dti_trilin' ...
    'outDir', pwd ...
);
dtiInit(config.dwi, config.t1, dwParams)

