#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=15gb,walltime=6:00:00
#PBS -N dtiinit

# Path to test dtiInit without additional registration
cp $(jq -r '.dwi' config.json) dwi_aligned_trilin_noMEC.nii.gz
cp $(jq -r '.bvecs' config.json) dwi_aligned_trilin_noMEC.bvecs
cp $(jq -r '.bvals' config.json) dwi_aligned_trilin_noMEC.bvals
cp identityXform.mat dwi_aligned_trilin_noMEC_acpcXform.mat

export FSLOUTPUTTYPE=NIFTI_GZ
singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/dtiinit
if [ ! -f product.json ];
then
    echo "failed to produce product.json"
    exit 1
fi

#dt6 is deprecated.. use product.json instead
cp product.json dt6.json

#app-dtiinit now outputs neuro/dwi. Let's copy (TODO - should I symlink?)
cp $(jq -r '.files.alignedDwRaw' product.json) dwi.nii.gz
cp $(jq -r '.files.alignedDwBvecs' product.json) dwi.bvecs
cp $(jq -r '.files.alignedDwBvals' product.json) dwi.bvals

#convert t1pdd.png to a webm movie
#gm convert -crop 181x217 t1pdd.png +adjoin t1pdd.%02d.png
#png2yuv -I p -f 24 -b 0 -n 98 -j t1pdd.%02d.png > t1pdd.yuv #mjpegtools
#vpxenc --good --cpu-used=0 --auto-alt-ref=1 --lag-in-frames=16 --end-usage=vbr --passes=2 --threads=2 --target-bitrate=3000 -o t1pdd.webm t1pdd.yuv #vpx-tools
