#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=6:00:00
#PBS -N dtiinit

#for karst/carbonate
module load singularity 2> /dev/null

singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/dtiinit

#check output file
if [ -f dt6.json ];
then
    echo 0 > finished
else
    echo "dt6.mat missing"
    echo 1 > finished
fi


